experiment_name: escapena1_h3ayfjdd_eval_wl40

random_state: 12345

tasks:
  -
    type: classification
    target: good_outcome
    metrics: [f1, precision, recall, specificity, auroc, auprc, accuracy]
    bootstrap: 1000
    ci: 95

model:
  name: SEResNext50Single
  checkpoint: wandb/run-20251207_003049-h3ayfjdd/files/SEResNext50Single.tar

data: 
  path: data/escapena1/test.csv
  modality: "B0_CTA"

batch_size: 1

preprocessing:
  spacing: [0.47, 0.47, 0.63]
  size: [278, 337, 221]
  # windowing:
  #   level: 250
  #   width: 400
  # normalize:
  #   mean: 50.78
  #   std: 6.18
  windowing:
    level: 40
    width: 80
  normalize:
    mean: 43.53
    std: 17.64